# Generated by Django 4.2.28 on 2026-03-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_sla_escalation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATED", "Ticket Created"),
                    ("ASSIGNED", "Ticket Assigned"),
                    ("RESOLVED", "Ticket Resolved"),
                    ("DELETED", "Ticket Deleted"),
                    ("COMMENTED", "Comment Added"),
                    ("REOPENED", "Ticket Reopened"),
                    ("CLOSED", "Ticket Closed"),
                    ("UPDATED", "Ticket Updated"),
                    ("STATUS", "Status Changed"),
                    ("PRIORITY", "Priority Changed"),
                    ("SYSTEM", "System Event"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taskhistory",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("UPDATED", "Updated"),
                    ("ASSIGNED", "Assigned"),
                    ("STATUS_CHANGED", "Status Changed"),
                    ("PRIORITY_CHANGED", "Priority Changed"),
                    ("COMMENTED", "Commented"),
                    ("REJECTED", "Rejected"),
                    ("DELETED", "Deleted"),
                    ("CLOSED", "Closed"),
                    ("REOPENED", "Reopened"),
                ],
                max_length=50,
            ),
        ),
    ]
